### ISSUE TITLE
Cannot upload Review PDF to ConfTool

### ISSUE THREAD

**Issue by mwidner** [dhlab-epfl/dhwriter#15]
Trying to submit the Review PDF, with no modifications, simply saved from the DHWriter site, to Conftool, I receive this error: "Error Uploading File
The uploaded file could not be interpreted. Either it is broken or in an unknown format.
Please check the file locally and retry, or contact the conference organizers." PDF was saved on a MacBook Pro running Mavericks.

**Comment by mwidner** [comment]
Also: opening the PDF in Acrobat Pro, then re-saving it fixed the error.

**Comment by cyrilbornet** [comment]
Could you provide me a sample of the faulty file by e-mail?
I couldn't reproduce this error using my test papers...

**Comment by cyrilbornet** [comment]
Should be fixed by now.
Tell me if it's not, I'll reopen the case.
Thank you.

**Comment by frederik-elwert** [comment]
I still get this error with a recently exported review PDF. How can I send you the file? Thanks.

**Comment by cyrilbornet** [comment]
Yes of course: support@dhwriter.org
Yours,
